### PR TITLE
Add tutorial dockers with slurm and pbs

### PR DESCRIPTION
**Pull request by MilBia**
Those PR add docker machines with SLURM and PBS to local machine tutorial purposes.
Both base on docker-compose and both are fully independent from local instance. To avoid any problems with user local changes, each container download our package from github.
Basic usage is self explaining I hope. Here's example:

`source tutorial/jupyter.sh`
`start_slurm`
`erase_slurm`
`start_pbs`
`erase_pbs`

After each start function, user can go to `localhost:8888` and use jupyter notebook. The root folder for notebook is our repository folder, so until user don't go to the terminal cannot even see other directories. After work, erase function stop and remove containers. Only thing what stay on user machine is docker images used to build containest.

**IMPORTANT**: In current version user can start only one, SLURM or PBS on once. That can be avoided by changing output port of one of them. The question is, do we want allow user to run that many containers at once?

What's important, user need to have configuration allowing use docker without sudo. In one case, when i need to use sudo, the usage become less pretty and look like that:

`sudo bash -c "$(declare -f start_slurm); start_slurm"`
`sudo bash -c "$(declare -f erase_slurm); erase_slurm"`
`sudo bash -c "$(declare -f start_pbs); start_pbs"`
`sudo bash -c "$(declare -f erase_pbs); erase_pbs"`

But maybe there are better ways to write that.

### CODE REVIEW

**Review by AdamWlodarczyk — COMMENTED** [review]
Look's good to me. 
@MilBia maybe you could add a section about it in README (what it does, how it works, how to start and shut it down)?

**Comment by ocaisa** [comment]
I gave this a first try. If possible it would be good if we reduce as much as possible the replication of things from the `ci` directory (symlinks perhaps?), maybe we can discuss in the next meeting.

In the documentation, it would be good to warn people that the total size that the tutorial will consume is >2.5GB. And they can clean this out with
```
docker system prune -a --volumes
```
(maybe this command is too much, it is pretty aggressive).

Also it would be good if you end up somewhere in the `tutorial` directory when you open your browser, like `tutorial/notebooks` (where we would put our notebooks for the tutorial).

One thing about `start_slurm` is that it requires that you run it from the root directory (if I run it inside the `tutorial` directory it fails), perhaps we can make it a bit more resilient than that?

**Comment by MilBia** [comment]
@ocaisa You are right I probably can cut off something more, I will take look on that. Measure the idle usage of memory and add that info to README. About reduce duplication, symlinks may be a solution. 

About `docker system prune -a --volumes`, I thing it is not a best idea to have that as ultimate solution. But I like idea of removing docker images related to tutorial. There probably is an option to remove them by name and tag like the way we refer to them to download. If that work I will add clean function with warning in README that remove all docker images related to tutorial.

Jupyter now is starting on our lib directory, because it work on independent copy from github master (in case user 'polute' local copy with anything) and there no exist any directory you mantions. Changing that is only one value in script and can be done in any moment when we achieve to have those files.

Correct, it works only from project root directory. I should try to improve that.

**Comment by MilBia** [comment]
@ocaisa I done everything you mention, except duplicate files.

I 100% agree that repository should not contain any additional files. But on other side, leaving those duplicates there make running dockers easier to understand for user who would like to see how we do that. Also on some moment in future those containers can evolve in other directions, what make common files a good place to generate errors.

I know that is only state of the art discussion, I just like to know other opinion.

**Comment by MilBia** [comment]
@ocaisa Thank you for edit. Are we required any other changes here?
That last comment is not a problem, it's just can be done. Just say.

**Comment by ocaisa** [comment]
@MilBia The last thing is that during the clean, there are still some things that we could remove (just a network for pbs, volumes and a network for slurm):
```
alanc@~/jobqueue_features(tutorial_docker)$ docker system prune -a --volumes
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all volumes not used by at least one container
  - all images without at least one container associated to them
  - all build cache

Are you sure you want to continue? [y/N] y
Deleted Networks:
pbs_default
slurm_default

Deleted Volumes:
slurm_var_lib_mysql
slurm_var_log_slurm
slurm_etc_munge
slurm_etc_slurm
slurm_slurm_jobdir

Total reclaimed space: 210.5MB

```
If you can fix that then I am happy to merge this.

**Comment by ocaisa** [comment]
@MilBia Can we add some tests to check that the docker containers build and work correctly (could be in another PR, no need to hold this back)

**Comment by MilBia** [comment]
@ocaisa I already run some of our ci tests on those machines to check if there work and realise those some tests were written too specific for travis. I will fix them in other PR, so I can add them also for thats containers.

**Comment by AdamWlodarczyk** [comment]
Looks good to me.

**Pull request merged**
