### PR TITLE
Update requirements

### PR DESCRIPTION
**Pull request by MilBia**
Specify exact versions for requirements to ensure project always work with the same checked configuration.

### CODE REVIEW

**Comment by MilBia** [comment]
Tutorial CI test will not work because its running cloned master branch.

**Comment by MilBia** [comment]
Travis is complaining about that line of code:
`                "Replaced command template\n\t{}\nwith\n\t{}\nin jobscript".format(`
He don't like `nin` fragment, but it's not a case in that PR and as I know is not an error.

**Review by AdamWlodarczyk — APPROVED** [review]

**Comment by ocaisa** [comment]
I'm not a fan of leaving broken CI in place. For the spelling issue you can add an option to https://github.com/E-CAM/jobqueue_features/blob/master/ci/none.sh#L23 : 
```
--ignore-words-list nin
```

**Comment by ocaisa** [comment]
Actually, should just kill Travis CI, there is no need to keep it around

**Comment by ocaisa** [comment]
@MilBia Can you remove the `.travis.yml` file in this PR as well?

**Comment by ocaisa** [comment]
> Tutorial CI test will not work because its running cloned master branch.

Where is that happening? Maybe we can fix that?

**Comment by ocaisa** [comment]
Ah, it is inherited from the container I guess.

In https://github.com/E-CAM/jobqueue_features/blob/master/ci/slurm/Dockerfile, can we just install our requirements to fix it? I don't understand what this is not a problem for the other CI, the containers are the same

**Comment by MilBia** [comment]
I don't remember why. We just make tutorial independent from local changes, by cloning to docker master branch. Those why tutorial CI, works only after changes in it go to the master.

**Comment by ocaisa** [comment]
Ok, I get it now, thanks

**Review by ocaisa — COMMENTED** [review]
LGTM

**Pull request merged**
