### PR TITLE
Dask jobqueue upgrade

### PR DESCRIPTION
**Pull request by AdamWlodarczyk**
Update code for `dask_jobqueue==0.7`. 
Mainly adapting attributes manipulation in `Job` objects which preciously were in `Cluster`.

### CODE REVIEW

**Comment by AdamWlodarczyk** [comment]
Still working on it. Some tests didn't pass.

**Comment by ocaisa** [comment]
@AdamWlodarczyk Any idea about
```
AttributeError: 'CustomSLURMCluster' object has no attribute 'status'
```
that is still appearing in the tests (even though they pass)

**Comment by ocaisa** [comment]
Seems it appeared elsewhere in jobqueue as well
https://github.com/dask/dask-jobqueue/issues/345

**Comment by AdamWlodarczyk** [comment]
@ocaisa I don't get it. The `Cluster` superclass actually has such attribute and it is used widely. I will try to work it out.

**Comment by AdamWlodarczyk** [comment]
This commit looks like naive way of dealing with that problem but in my opinion it solves it correctly. The cluster is closed which is the most important part. It is also removed from clusters collection so garbage collector should properly handle it. It is interesting that those `__del__` calls are made on almost destructed object since it has no arguments (e.g. `status` or `scheduler_comm`).

**Review by ocaisa — APPROVED** [review]

**Pull request merged**
