### PR TITLE
Allow PBS CI to create workers

### PR DESCRIPTION
**Pull request by ocaisa**

### CODE REVIEW

**Comment by ocaisa** [comment]
@AdamWlodarczyk In https://github.com/E-CAM/jobqueue_features/pull/54/commits/1c17093a8381192031a2ddbbb61dc1c0b6416f2a I wanted to clean up some warnings and it has now triggered a failing test that I cannot figure out

**Comment by ocaisa** [comment]
@AdamWlodarczyk I can fix the problem with https://github.com/E-CAM/jobqueue_features/pull/54/commits/7d0fba91eb918e60a5ed62186bdee226e1c5d7cd but I really don't understand why that is not allowed. Not closing the local cluster seems to kick a lot of warnings

**Comment by AdamWlodarczyk** [comment]
@ocaisa this is strange. I don't understand it either. I will take a look at it on the weekend.

**Comment by AdamWlodarczyk** [comment]
@ocaisa, I'm still debugging that and this is super strange. Somehow multiple closing and therefore multiple local cluster creation influences the mpi task subprocess execution since it returns the `returncode == 1`.

**Comment by AdamWlodarczyk** [comment]
@ocaisa, news from the front. If you'd comment out the `test_flush_and_abort` test and `test_mpi_deserialize_and_execute` then remaining test (especially the `test_mpi_wrap_execution` where problems appeared) are passing. So the problem lays in those two. Probably. I'll keep on looking.

**Comment by AdamWlodarczyk** [comment]
`set_task_mpi_comm` and `flush_and_abort` functions from `mpi_wrapper.py` seem to make troubles. 
Both have in common the import line `from mpi4py import MPI`.

**Comment by ocaisa** [comment]
@AdamWlodarczyk Ok, maybe there is some sense here, there may be some environment variables set by `mpi4py` that don't allow `mpiexec` to run. I'll play around with it a bit

**Comment by ocaisa** [comment]
I think I could get this to work if I could enforce an order, I'm trying to that but I'm failing

**Comment by ocaisa** [comment]
@AdamWlodarczyk Ok, I have something that works, there is a warning that I would like to ignore but I don't know how to do that.

**Comment by AdamWlodarczyk** [comment]
@ocaisa https://github.com/ftobia/pytest-ordering/issues/57 mentions that warning. Well, let's count on them to fix it.

**Comment by AdamWlodarczyk** [comment]
Added just small change.

**Comment by ocaisa** [comment]
@AdamWlodarczyk This still needs a small amount of work, I tried to execute an MPI job on the slaves and it didn't work, I'll figure it out tomorrow.

**Comment by ocaisa** [comment]
@AdamWlodarczyk ok, good to go now

**Review by AdamWlodarczyk — APPROVED** [review]

**Pull request merged**
