### PR TITLE
Ensure to connect to available port (fix: #97)

### PR DESCRIPTION
**Pull request by AdamWlodarczyk**

### CODE REVIEW

**Comment by AdamWlodarczyk** [comment]
If you think that it could be done better let me know. I'm not experienced with docker TBH.

**Comment by MilBia** [comment]
If we want to try to save the port `8888` (or one of the next) as a host it's nice approach.
If we just want it to be any of host ports, we can just:
`"${SLURMCTLD_OUT_PORT}:8888"` -> `"8888"`
and save as our `port` variable result of following:
`docker port slurmctld 8888 | cut -d ":" -f2`

**Comment by ocaisa** [comment]
I think we should do the same for port 8787, there is a chance this is also occupied on the host, we can then say
```
echo -e "\tOpen your browser at http://localhost:$port/lab/workspaces/lab (default Dask dashboard will be available at http://localhost:$daskport)"
```

**Comment by AdamWlodarczyk** [comment]
Thanks @MilBia – I think this is a better solution, though it yields some less organized port numbers like 32768. But that is why we print it out. Perfect :superhero:

**Comment by MilBia** [comment]
LGTM

**Comment by ocaisa** [comment]
Tested in my setup and worked fine, thanks @AdamWlodarczyk

**Pull request merged**
