### PR TITLE
Change type annotations

### PR DESCRIPTION
**Pull request by AdamWlodarczyk**
Change type annotations since letting go older python versions.

### CODE REVIEW

**Comment by AdamWlodarczyk** [comment]
I don't get it. There must be some customized black settings.

**Comment by ocaisa** [comment]
Maybe we need to update the action we use? https://github.com/E-CAM/jobqueue_features/blob/6b8b00d5ee4e3ba61bb299414c200f713702dc65/.github/workflows/ci.yaml#L25

**Comment by AdamWlodarczyk** [comment]
> I don't get it. There must be some customized black settings.

Looks that I was right, but not the way I thought so :wink: My local black settings were set to 100 characters limit per line.

**Review by ocaisa — APPROVED** [review]
LGTM

**Pull request merged**
