### PR TITLE
Add dask labextensionto to tutorial docker

### PR DESCRIPTION
**Pull request by MilBia**
Add dask labextensionto extension to tutorial docker.

### CODE REVIEW

**Comment by ocaisa** [comment]
@MilBia It works but it needs additional configuration to be able to start up a cluster on the worker nodes

**Comment by ocaisa** [comment]
See https://github.com/dask/dask-labextension#configuration-of-dask-cluster-management

**Comment by MilBia** [comment]
I add that config, but don't understood how it's truly work.
If anyone have any suggestion what to add/change, I'll be thankful.

**Comment by ocaisa** [comment]
The configuration file doesn't seem to be working, but I don't know why. Everything else is good though for me.

**Comment by MilBia** [comment]
I'm working on it. To configuration start to work jupyter need to be restarted. Work in progress to do that automatically on starting. ;)

**Comment by MilBia** [comment]
That should work. At least works for me. Please check and confirm or describe error if You acure any.

**Comment by ocaisa** [comment]
Worked for me too. There are a few hiccups (when started via GUI cluster doesn't scale and is not accessible in the plugin without putting in the URL) but I think these are not important to use since we expect people to start the clusters in their browser.

**Review by ocaisa — APPROVED** [review]
LGTM

**Comment by MilBia** [comment]
If I good understood the problem. If during using any of notebooks you click magnifier (even without passing URL) after run connection to cluster, plugin should connect to the cluster too. If it's not started from GUI it wouldn't be seen on the list, but still should be able to show graphs and other parameters during computing.

**Comment by ocaisa** [comment]
Yes, I could see stuff in the GUI when I started the cluster myself in a notebook, all that worked fine

**Pull request merged**
